apiVersion: v1
kind: Pod 
metadata: 
  name: pod2
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "name"
      operator: "Equal"
      value: "node2"
      effect: "PreferNoSchedule"
